package person;

public class Person2 {
    private String name;
    private int yearOfBirth;

    public Person2 (String name) {
        this.name = name;
        getYear();
    }

    public static void main(String[] args) {

        Person2 person2 = new Person2("Kasia");

        //Na koniec - przypadek, w którym w konstruktorze jest jeden parametr w nawiasach () a drugi  w postaci metody tworzącej go w "jakiś sposób" np. losowo

        /*  X  person created by compiler from constructor with first parameter provided in constructor and second
         being generated by random generator "getYear"  */
        Person personCaseX = new Person("Kasia");
        System.out.println("Name of Person X: " + person2.name + ",  born in : " + person2.yearOfBirth + " year");
    }

        public void getYear(){
            int max = 2000;
            int min = 1900;
            this.yearOfBirth = (int)Math.floor(Math.random()*(max-min+1)+ min);
        }
}